name: Generate 3D Contribution SVG

on:
  schedule:       # 매일 18:00 UTC 실행(원하는 크론으로 바꿔도 됨)
    - cron: "0 05 * * *"
  workflow_dispatch:  # 수동 실행

permissions:
  contents: write     # GITHUB_TOKEN으로 커밋/푸시하려면 필요

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 기본 토큰으로도 충분

      - name: Generate 3D contribution svgs
        uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      # env에 넣는다
          USERNAME: ${{ github.repository_owner }}       # 보통 본인 아이디

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "chore: update 3D contribution svgs" || echo "No changes"
          git push
